### ISSUE TITLE
[dev-kit] Autogen `libedit` and fix for GCC 14.3

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#615]
Building our `libedit-20170329.3.1` with `gcc-14.3.0` fails with the following error:
```
/var/tmp/portage/dev-libs/libedit-20170329.3.1/work/libedit-20170329-3.1/src/filecomplete.c: In function ‘sh_find_word_start’:
/var/tmp/portage/dev-libs/libedit-20170329.3.1/work/libedit-20170329-3.1/src/filecomplete.c:606:33: error: passing argument 1 of ‘strchr’ from incompatible pointer type [-Wincompatible-pointer-types]
  606 |                 else if (strchr(break_chars, *buffer))
      |                                 ^~~~~~~~~~~
      |                                 |
      |                                 const wchar_t * {aka const int *}
```

There is a newer version `libedit-20251016-3.1` that we can obtain from here: https://www.thrysoee.dk/editline/

We should autogen this package and see if the new version builds with `gcc-14.3.0`; otherwise, we will need a patch.
