### ISSUE TITLE
[core-server-kit] [emerge] `media-sound/mpd` dependency `sys-libs/liburing` fails compile

### ISSUE THREAD

**Issue by jiggie42** [macaroni-os/mark-issues#184]
in an attempt to investigate #183 I was blocked by this failing dependency.  I was able to proceed by simply bumping the version of liburing, so it is a good candidate for autogenning.

`ucontext-cp.c:31:23: error: variably modified ‘stack_buf’ at file scope
   31 |         unsigned char stack_buf[SIGSTKSZ];
      |                       ^~~~~~~~~
make[1]: *** [Makefile:20: ucontext-cp] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/portage/sys-libs/liburing-0.7/work/liburing-0.7/examples'
make: *** [Makefile:14: all] Error 2
 * ERROR: sys-libs/liburing-0.7::core-server-kit failed (compile phase):
 *   emake failed
`

**Comment by jiggie42** [comment]
I understand `gearu-kit` has a newer version that works, so that might be a better candidate to work from.
Having compared our old liburing-0.7.ebuild with gentoo's liburing-2.7.ebuild I would point out the following changes

> SLOT="0/2" # liburing.so major version

also within src_configure they added
> 	--cxx="$(tc-getCXX)"
> 	--use-libc

**Comment by geaaru** [comment]
Yeah, i confirm. Macaroni Phoenix using my `liburing` version:
```
$ anise s liburing --table
|      PACKAGE      | VERSION |        REPOSITORY        |
|-------------------|---------|--------------------------|
| sys-libs/liburing | 2.3     | macaroni-phoenix-testing |
```
